export const actions={
    profile:{
        "DATA_FETCHING":"PROFILE_DATA_FETCHING",
        "DATA-FETCHED":"PROFILE_DATA_FETCHED",
        "DATA_FETCH-ERROR":"PROFILE_DATA-FETCH_ERROR",
        "USER-DATA_EDITED" :"PROFILE_USER_DATA_EDITED",
        "IMAGE_UPDATED":"PROFILE_IMAGE_UPDATED"
    },
        post:{
        "DATA_FETCHING":"POST_DATA_FETCHING",
        "DATA-FETCHED":"POST_DATA_FETCHED",
        "DATA_FETCH-ERROR":"POST_DATA-FETCH_ERROR",
        "DATA_CREATED":"POST_DATA_CREATED",
        "DATA_EDITED" :"POST_USER_DATA_EDITED",
        "POST-DELETED":"POST_DATA_DELETED",
    },


}